/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DisintegrateTokens = IDL.Nat;
export const Balance = IDL.Tuple(IDL.Principal, DisintegrateTokens);
export const Time = IDL.Int;
export const BurnAmount = IDL.Nat;
export const BurnTransaction = IDL.Tuple(Time, BurnAmount);

export const idlService = IDL.Service({
  'claimTokens' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'getAllBalances' : IDL.Func([], [IDL.Vec(Balance)], ['query']),
  'getAllBalancesSorted' : IDL.Func([], [IDL.Vec(Balance)], ['query']),
  'getAllBurnEvents' : IDL.Func([], [IDL.Vec(BurnTransaction)], ['query']),
  'getAllBurnEventsByAmount' : IDL.Func(
      [],
      [IDL.Vec(BurnTransaction)],
      ['query'],
    ),
  'getBalance' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DisintegrateTokens)],
      ['query'],
    ),
  'getBurnAmount' : IDL.Func([Time], [BurnAmount], ['query']),
  'getBurnEventsInRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(BurnTransaction)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DisintegrateTokens = IDL.Nat;
  const Balance = IDL.Tuple(IDL.Principal, DisintegrateTokens);
  const Time = IDL.Int;
  const BurnAmount = IDL.Nat;
  const BurnTransaction = IDL.Tuple(Time, BurnAmount);
  
  return IDL.Service({
    'claimTokens' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'getAllBalances' : IDL.Func([], [IDL.Vec(Balance)], ['query']),
    'getAllBalancesSorted' : IDL.Func([], [IDL.Vec(Balance)], ['query']),
    'getAllBurnEvents' : IDL.Func([], [IDL.Vec(BurnTransaction)], ['query']),
    'getAllBurnEventsByAmount' : IDL.Func(
        [],
        [IDL.Vec(BurnTransaction)],
        ['query'],
      ),
    'getBalance' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DisintegrateTokens)],
        ['query'],
      ),
    'getBurnAmount' : IDL.Func([Time], [BurnAmount], ['query']),
    'getBurnEventsInRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(BurnTransaction)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };